import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Election Dashboard",
  description: "Generated by create next app",
};
//  className={inter.className}
// 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      {children}
      </body>
    </html>
  );
}
